# Generated by Django 3.2.4 on 2021-07-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Therapist', 'Терапевт'), ('Surgeon', 'Хирург')], default='Therapist', max_length=9, verbose_name='Терапевт/Хирург')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pin', models.CharField(max_length=14, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Лечащий врач',
                'verbose_name_plural': 'Лечащие врачи',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.CharField(choices=[('Chui', 'Чуйская'), ('IK', 'Иссык-Кульская'), ('Talas', 'Таласская'), ('Naryn', 'Нарынская'), ('Osh', 'Ошская'), ('Batken', 'Баткенская')], default='Chui', max_length=9, verbose_name='Область')),
                ('ocpo', models.CharField(max_length=4, unique=True, verbose_name='ОКПО')),
                ('gov', models.BooleanField(default=False, verbose_name='Государственное')),
            ],
            options={
                'verbose_name': 'Больница',
                'verbose_name_plural': 'Больницы',
            },
        ),
        migrations.CreateModel(
            name='MainDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pin', models.CharField(max_length=14, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Главрач',
                'verbose_name_plural': 'Главрачи',
            },
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pin', models.CharField(max_length=14, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Медсестра',
                'verbose_name_plural': 'Медсестры',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pin', models.CharField(max_length=14, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('why', models.CharField(max_length=200, verbose_name='Причина обращения в больницу')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.doctor', verbose_name='Лечащий врач')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.hospital', verbose_name='Больница')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.nurses', verbose_name='Медсестра')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.maindoctor', verbose_name='Главрач'),
        ),
    ]
