# Generated by Django 3.2.4 on 2021-07-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='nurse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.nurses', verbose_name='Медсестра'),
        ),
    ]
