# Generated by Django 3.2.4 on 2021-07-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_doctor_nurse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='doctor',
            new_name='doctors',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.hospital', verbose_name='Больница'),
        ),
    ]
