# Generated by Django 3.2.4 on 2021-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_auto_20210706_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.CharField(choices=[('Терапевт', 'Терапевт'), ('Хирург', 'Хирург')], default='Терапевт', max_length=9, verbose_name='Терапевт/Хирург'),
        ),
    ]
