# Generated by Django 3.2.4 on 2021-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_alter_doctor_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(choices=[('Пациент', 'Пациент'), ('Медсестра', 'Медсестра'), ('Врач', 'Врач'), ('Главрач', 'Главрач')], default='Врач', max_length=11)),
            ],
        ),
    ]
