# Generated by Django 3.2.4 on 2021-07-12 02:24

import HospitalApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0006_delete_rang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nurse',
            field=models.ForeignKey(default=HospitalApp.models.random_nurse, on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.nurses', verbose_name='Медсестра'),
        ),
    ]
