# Generated by Django 3.2.4 on 2021-07-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0007_alter_doctor_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='HospitalApp.doctor', verbose_name='Лечащий врач'),
        ),
    ]
