# Generated by Django 3.2.4 on 2021-07-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0009_hospital_maxn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='HospitalApp.maindoctor', verbose_name='Главрач'),
        ),
    ]
