# Generated by Django 3.2.4 on 2021-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0010_alter_hospital_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='maxn',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2, verbose_name='Макс.число работников'),
        ),
    ]
