# Generated by Django 3.2.4 on 2021-07-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0011_alter_hospital_maxn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='maxn',
        ),
    ]
