# Generated by Django 3.2.4 on 2021-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0012_remove_hospital_maxn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='maxn',
            field=models.IntegerField(default=100, verbose_name='Макс.количество сотрудников'),
        ),
    ]
